# === Rust Playground ===
[package]
name = "ndarray"
version = "0.1.0"
authors = ["Kan Murata <kan@murakan.info>"]
edition = "2018"

[dependencies]
byteorder = "1.4.3"
ndarray = "*"
ndarray-rand = "0.14.0"
tempfile = "3.7.1"
