# === Rust Playground ===
[package]
name = "hex_dump"
version = "0.1.0"
authors = ["Kan Murata <kan@murakan.info>"]
edition = "2018"

[dependencies]
bincode = "1.3.3"
rand = "0.8.5"
serde = "1.0.176"
serde_cbor = "0.11.2"
serde_derive = "1.0.176"
serde_json = "1.0.104"
